PIDs:
  X:
    kp: 10.0
    kd: 0.0
    ki: 1.0
    minOutput: -10.0
    maxOutput: 10.0
    integratorMin: -0.1
    integratorMax: 0.1
  Y:
    kp: -10.0
    kd: -0.0
    ki: -1.0
    minOutput: -10.0
    maxOutput: 10.0
    integratorMin: -0.1
    integratorMax: 0.1
  Z:
    kp: 2000.0
    kd: 0.0
    ki: 1000.0
    minOutput: 10000.0
    maxOutput: 55000.0
    integratorMin: -1000.0
    integratorMax: 1000.0
  Yaw:
    kp: -200.0
    kd: -20.0
    ki: 0.0
    minOutput: -200.0
    maxOutput: 200.0
    integratorMin: 0.0
    integratorMax: 0.0
